### ISSUE TITLE
Incorrect layout generated for notebook containing nested sizers

### ISSUE THREAD

**Issue by reticulatus** [wxGlade/wxGlade#554]
I was updating an old interface which consists of a dialog containing a notebook, which contains 3 nested sizers each of which holds a BitmapButton, 3 StaticTexts and 3 SpinCtrls.

The layout looks OK in the design window. 

In the preview window and on running the code, the BitmapButtons are located the correct sizers, but all the groups of StaticTexts and SpinCtrls appear to be on the notebook pane itself.

I notice in the generated code, the BitmapButtons have the return value from a call to their sizer's GetStaticBox() method as their parent.

However, the StaticTexts and SpinCtrls are all passed self.colour_pane as their parent.

I have created a cut down example which demonstrates the issue and put its files in the attached zip file:
[notebook_nested_sizers.zip](https://github.com/user-attachments/files/16564932/notebook_nested_sizers.zip)

I am using wxGlade 1.1.0b1 (from the master branch) with Python 3.12.3 and wxPython 4.2.1 on Linux Mint 22.

**Comment by DietmarSchwertberger** [comment]
Thanks for reporting. I can probably look into this next week.

**Comment by DietmarSchwertberger** [comment]
This is probably the minimum sample to reproduce the issue:
[nested_sizers_min_1.wxg.txt](https://github.com/user-attachments/files/16565504/nested_sizers_min_1.wxg.txt)

This is the point where the code generation is wrong (for Python), as it check only the direct parent for being a StaticBoxSizer:
```
        elif self.codegen.for_version[0]>=3 and obj.sizer and obj.sizer.WX_CLASS=="wxStaticBoxSizer":
            sizer_access = self.format_widget_access(obj.sizer)
            self.tmpl_dict['parent'] = '%s.GetStaticBox()' % sizer_access
```

The fix will require to keep a reference to `...GetStaticBox())` also deeper in the hierarchy when the direct parent is a different sizer.

**Comment by DietmarSchwertberger** [comment]
It should be fixed now in the repository.

**Comment by reticulatus** [comment]
I downloaded the latest version from master branch and used it to open both the original `notebook_nested_sizers.wxg` file I posted and the `nested_sizers_min_1.wxg` that you posted.

In both cases the controls that should be in the inner sizers are still appearing on the panel when viewed in the Preview window.

When I compare the generated python code for my example, it is identical to what I had before, apart from the timestamp in line 4.

**Comment by reticulatus** [comment]
I notice there is a new method `get_parent_window2()` in `edit_base.py`, but I can't find anywhere that calls it?

**Comment by DietmarSchwertberger** [comment]
Oh, yes, sorry. I missed to add the changed lines in wcodegen to the commit. Too many files in the working directory...

**Comment by reticulatus** [comment]
Confirmed, all my tests are working now.
Thank you.
